apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-prod
  namespace: openshift-gitops
spec:
  destination:
    namespace: bookinfo-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/prod
    repoURL: https://github.com/cwilkers/gitopscon22
    targetRevision: prod
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - Replace=true
